/*
 * Generated by scripts/dataverse/generate-choicemap.mjs — do not edit.
 *
 * Maps each choice column to its option labels and integer values, keyed by
 * Dataverse entity set name (the same string used as `dataSource` in
 * tableMap.ts). Regenerate with `npm run dataverse:choices` after any change
 * to a choice column.
 */

/**
 * Every bv_* entity set in the environment. Dataverse pluralises names
 * itself and does not always agree with English — bv_soilanalysis becomes
 * bv_soilanalysises — so a hand-written dataSource is easy to get wrong, and
 * the failure looks like an empty screen rather than an error.
 */
export const ENTITY_SETS: readonly string[] = [
  "bv_availabilities",
  "bv_beds",
  "bv_boxweights",
  "bv_cainumbers",
  "bv_calendars",
  "bv_components",
  "bv_customers",
  "bv_demandforecasts",
  "bv_expenses",
  "bv_fertilizations",
  "bv_fields",
  "bv_fiscalauthorizations",
  "bv_foliaranalysises",
  "bv_harvests",
  "bv_inputcomponents",
  "bv_inputs",
  "bv_invoices",
  "bv_irrigations",
  "bv_nutrientbalances",
  "bv_orderitems",
  "bv_orders",
  "bv_packings",
  "bv_plantings",
  "bv_plantprices",
  "bv_plants",
  "bv_pruningcurves",
  "bv_prunings",
  "bv_purchaseorders",
  "bv_seasons",
  "bv_shadehouses",
  "bv_soilanalysises",
  "bv_suppliers",
  "bv_tasks",
  "bv_timesheets",
  "bv_treatments",
  "bv_workers"
];

/** entity set -> column -> { label: optionValue } */
export const CHOICE_MAP: Record<string, Record<string, Record<string, number>>> = {
  "bv_availabilities": {
    "bv_size": {
      "Petit": 187460000,
      "Mini Petit": 187460001,
      "Small": 187460002,
      "Medium": 187460003,
      "California": 187460004,
      "Large": 187460005,
      "Extra Large": 187460006
    },
    "bv_status": {
      "Projected": 187460000,
      "Confirmed - Under": 187460001,
      "Confirmed - Equal": 187460002,
      "Confirmed - Over": 187460003
    }
  },
  "bv_beds": {
    "bv_bedmaterial": {
      "Wood": 121320000,
      "Concrete": 121320001,
      "Plastic": 121320002,
      "Metal": 121320003
    },
    "bv_drainage": {
      "Excellent": 121320000,
      "Good": 121320001,
      "Moderate": 121320002,
      "Poor": 121320003
    },
    "bv_irrigationtype": {
      "Drip": 121320000,
      "Sprinkler": 121320001,
      "Manual": 121320002,
      "None": 121320003
    },
    "bv_level": {
      "0": 121320000,
      "1": 121320001,
      "2": 121320002,
      "3": 121320003
    },
    "bv_soiltype": {
      "Sandy": 121320000,
      "Loamy": 121320001,
      "Clay": 121320002,
      "Peaty": 121320003,
      "Chalky": 121320004,
      "Silty": 121320005
    },
    "bv_type": {
      "Air": 121320000,
      "Ground": 121320001
    }
  },
  "bv_cainumbers": {
    "bv_usedfor": {
      "Export Invoice (BANCO)": 187460000,
      "Internal Invoice (JASON)": 187460001,
      "Service Invoice": 187460002,
      "Other": 187460003
    }
  },
  "bv_components": {
    "bv_category": {
      "Macronutrient": 121320300,
      "Secondary nutrient": 121320301,
      "Micronutrient": 121320302,
      "Active ingredient": 121320303,
      "Organic / biostimulant": 121320304,
      "Carrier / inert": 121320305,
      "Other": 121320306
    }
  },
  "bv_customers": {
    "bv_paymentterms": {
      "CIF": 187460000,
      "FOB": 187460001,
      "EXW": 187460002,
      "DDP": 187460003,
      "Net 30": 187460004
    }
  },
  "bv_demandforecasts": {
    "bv_requesttype": {
      "Current Order": 187460000,
      "Additional Request": 187460001,
      "Additional Order": 187460002
    },
    "bv_status": {
      "Pending": 187460000,
      "Confirmed": 187460001,
      "Adjusted": 187460002,
      "Cancelled": 187460003
    }
  },
  "bv_expenses": {
    "bv_category": {
      "Supplies": 187460000,
      "Equipment": 187460001,
      "Labor": 187460002,
      "Transportation": 187460003,
      "Utilities": 187460004,
      "Chemicals / Inputs": 187460005,
      "Shipping / Freight": 187460006,
      "Maintenance": 187460007,
      "Office": 187460008,
      "Other": 187460009
    },
    "bv_currency": {
      "HNL": 187460000,
      "USD": 187460001
    },
    "bv_status": {
      "Pending": 187460000,
      "Approved": 187460001,
      "Rejected": 187460002,
      "Paid": 187460003
    }
  },
  "bv_fertilizations": {
    "bv_doseunit": {
      "kg": 121320220,
      "L": 121320221,
      "g": 121320222,
      "mL": 121320223
    },
    "bv_method": {
      "Foliar Spray": 187460000,
      "Soil Drench": 187460001,
      "Granular": 187460002,
      "Drip / Fertigation": 187460003,
      "Broadcast": 187460004
    }
  },
  "bv_harvests": {
    "bv_quality": {
      "Excellent": 187460000,
      "Good": 187460001,
      "Average": 187460002,
      "Poor": 187460003
    }
  },
  "bv_inputs": {
    "bv_applicationmethod": {
      "Foliar Spray": 187460000,
      "Soil Drench": 187460001,
      "Granular": 187460002,
      "Drip": 187460003,
      "Broadcast": 187460004,
      "Other": 187460005
    },
    "bv_formulation": {
      "Solid": 121320210,
      "Soluble powder": 121320211,
      "Liquid": 121320212,
      "Suspension": 121320213
    },
    "bv_inputcategory": {
      "Fertilizer": 187460000,
      "Pesticide": 187460001,
      "Fungicide": 187460002,
      "Herbicide": 187460003,
      "Growth Regulator": 187460004,
      "Other": 187460005
    }
  },
  "bv_invoices": {
    "bv_shippedvia": {
      "Air": 187460000,
      "Sea": 187460001,
      "Land": 187460002
    },
    "bv_status": {
      "Draft": 187460000,
      "Sent": 187460001,
      "Partially Paid": 187460002,
      "Paid": 187460003,
      "Overdue": 187460004,
      "Cancelled": 187460005
    },
    "bv_terms": {
      "CIF": 187460000,
      "FOB": 187460001,
      "EXW": 187460002,
      "DDP": 187460003
    }
  },
  "bv_irrigations": {
    "bv_method": {
      "Drip": 187460000,
      "Sprinkler": 187460001,
      "Manual": 187460002,
      "Flood": 187460003
    },
    "bv_source": {
      "Controller": 121320110,
      "Manual": 121320111
    },
    "bv_status": {
      "Running": 121320100,
      "Completed": 121320101,
      "Fault": 121320102,
      "Aborted": 121320103
    }
  },
  "bv_orders": {
    "bv_status": {
      "Draft": 187460000,
      "Confirmed": 187460001,
      "In Packing": 187460002,
      "Ready for Pickup": 187460003,
      "Delivered": 187460004,
      "Cancelled": 187460005
    }
  },
  "bv_packings": {
    "bv_cuttingtype": {
      "L/E": 187460000
    },
    "bv_packingtype": {
      "BNDL": 125690000,
      "IND": 125690001
    },
    "bv_producttype": {
      "URC": 187460000
    },
    "bv_size": {
      "Petit": 187460000,
      "Mini Petit": 187460001,
      "Small": 187460002,
      "Medium": 187460003,
      "California": 187460004,
      "Large": 187460005,
      "Extra Large": 187460006
    }
  },
  "bv_plants": {
    "bv_growthhabit": {
      "Upright": 121320000,
      "Spreading": 121320001,
      "Climbing": 121320002,
      "Trailing": 121320003
    },
    "bv_propagationmethod": {
      "Seed": 121320000,
      "Cutting": 121320001,
      "Division": 121320002,
      "Grafting": 121320003,
      "Tissue Culture": 121320004
    },
    "bv_soiltype": {
      "Sandy": 121320000,
      "Loamy": 121320001,
      "Clay": 121320002,
      "Peaty": 121320003,
      "Chalky": 121320004,
      "Silty": 121320005
    },
    "bv_sunlightrequirement": {
      "Full Sun": 121320000,
      "Partial Shade": 121320001,
      "Full Shade": 121320002
    },
    "bv_waterrequirement": {
      "Low": 121320000,
      "Medium": 121320001,
      "High": 121320002
    }
  },
  "bv_purchaseorders": {
    "bv_currency": {
      "HNL": 187460000,
      "USD": 187460001
    },
    "bv_status": {
      "Draft": 187460000,
      "Sent": 187460001,
      "Confirmed": 187460002,
      "Received": 187460003,
      "Cancelled": 187460004
    }
  },
  "bv_suppliers": {
    "bv_category": {
      "Chemicals / Inputs": 187460000,
      "Packaging": 187460001,
      "Equipment": 187460002,
      "Substrates": 187460003,
      "Logistics / Freight": 187460004,
      "Maintenance": 187460005,
      "Utilities": 187460006,
      "Professional Services": 187460007,
      "Other": 187460008
    },
    "bv_paymentterms": {
      "Cash": 187460000,
      "Net 15": 187460001,
      "Net 30": 187460002,
      "Net 60": 187460003,
      "Credit": 187460004
    }
  },
  "bv_tasks": {
    "bv_priority": {
      "Low": 187460000,
      "Normal": 187460001,
      "High": 187460002,
      "Urgent": 187460003
    },
    "bv_status": {
      "Pending": 187460000,
      "In Progress": 187460001,
      "Done": 187460002,
      "Skipped": 187460003
    },
    "bv_tasktype": {
      "Watering": 187460000,
      "Fertilizing": 187460001,
      "Pruning": 187460002,
      "Repotting": 187460003,
      "Pest Control": 187460004,
      "Disease Treatment": 187460005,
      "Harvesting": 187460006,
      "Seeding": 187460007,
      "Packing": 187460008,
      "Inspection": 187460009,
      "General Maintenance": 187460010
    }
  },
  "bv_timesheets": {
    "bv_activitytype": {
      "Planting": 187460000,
      "Harvesting": 187460001,
      "Packing": 187460002,
      "Treatment": 187460003,
      "Irrigation": 187460004,
      "Maintenance": 187460005,
      "General": 187460006
    }
  },
  "bv_treatments": {
    "bv_doseunit": {
      "kg": 121320230,
      "L": 121320231,
      "g": 121320232,
      "mL": 121320233
    },
    "bv_type": {
      "Insecticide": 187460000,
      "Fungicide": 187460001,
      "Herbicide": 187460002,
      "Regulator": 187460003
    }
  },
  "bv_workers": {
    "bv_role": {
      "Field Worker": 187460000,
      "Packer": 187460001,
      "Harvester": 187460002,
      "Irrigator": 187460003,
      "Supervisor": 187460004,
      "Driver": 187460005,
      "General": 187460006
    }
  }
};

/** Reverse lookup, built once: entity set -> column -> { optionValue: label }. */
export const CHOICE_LABELS: Record<string, Record<string, Record<number, string>>> =
  Object.fromEntries(
    Object.entries(CHOICE_MAP).map(([entitySet, columns]) => [
      entitySet,
      Object.fromEntries(
        Object.entries(columns).map(([column, byLabel]) => [
          column,
          Object.fromEntries(Object.entries(byLabel).map(([label, value]) => [value, label])),
        ])
      ),
    ])
  );
