/**
 * GENERATED by scripts/dataverse/generate-rowtypes.mjs — do not edit.
 *
 * One interface per table the app reads, built from the Dataverse schema and
 * the field map in tableMap.ts. Every column is optional because Dataverse
 * returns nothing for an empty cell; only `id` is always present.
 *
 * Regenerate with: npm run dataverse:rowtypes
 */

export interface BalanceRow {
  id: string;
  bed?: string;
  week?: number;
  nApplied?: number;
  pApplied?: number;
  kApplied?: number;
  caApplied?: number;
  nExtracted?: number;
  pExtracted?: number;
  kExtracted?: number;
  caExtracted?: number;
  dryMatterPct?: number;
  primaryName?: string;
  [key: string]: unknown;
}

export interface BankAccountsRow {
  id: string;
  code?: string;
  name?: string;
  bank?: string;
  accountNumber?: string;
  currency?: string;
  openingBalance?: number;
  active?: boolean;
  notes?: string;
  [key: string]: unknown;
}

export interface BedCompositionsRow {
  id: string;
  bed?: string;
  material?: string;
  percentage?: number;
  notes?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface BedCountsRow {
  id: string;
  bed?: string;
  plant?: string;
  season?: string;
  week?: number;
  counted?: number;
  countDate?: string;
  countedBy?: string;
  notes?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface BedsRow {
  id: string;
  name?: string;
  active?: boolean;
  location?: string;
  type?: string;
  level?: string;
  shade?: string;
  soilType?: string;
  drainage?: string;
  irrigationType?: string;
  field?: string;
  [key: string]: unknown;
}

export interface BillsRow {
  id: string;
  number?: string;
  poRef?: string;
  rtn?: string;
  date?: string;
  dueDate?: string;
  subtotal?: number;
  isv?: number;
  total?: number;
  paid?: number;
  balance?: number;
  currency?: string;
  status?: string;
  notes?: string;
  supplier?: string;
  purchaseOrder?: string;
  [key: string]: unknown;
}

export interface CaiNumbersRow {
  id: string;
  name?: string;
  sequence?: number;
  used?: boolean;
  usedDate?: string;
  notes?: string;
  fiscalAuth?: string;
  invoice?: string;
  [key: string]: unknown;
}

export interface ComponentsRow {
  id: string;
  name?: string;
  symbol?: string;
  category?: string;
  elementSymbol?: string;
  elementalFactor?: number;
  isNutrient?: boolean;
  [key: string]: unknown;
}

export interface CurveRow {
  id: string;
  season?: string;
  week?: number;
  plannedBeds?: number;
  actualBeds?: number;
  plannedCuttings?: number;
  actualCuttings?: number;
  primaryName?: string;
  [key: string]: unknown;
}

export interface CustomersRow {
  id: string;
  code?: string;
  name?: string;
  contact?: string;
  contactEmail?: string;
  email?: string;
  phone?: string;
  address?: string;
  taxId?: string;
  deliverToName?: string;
  deliverToAddress?: string;
  terms?: string;
  notes?: string;
  active?: boolean;
  [key: string]: unknown;
}

export interface DemandForecastsRow {
  id: string;
  customer?: string;
  plant?: string;
  size?: string;
  requestType?: string;
  week?: number;
  year?: number;
  requested?: number;
  confirmed?: number;
  status?: string;
  quarter?: string;
  batch?: string;
  notes?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface ExchangeRatesRow {
  id: string;
  code?: string;
  date?: string;
  value?: number;
  source?: string;
  notes?: string;
  [key: string]: unknown;
}

export interface ExpensesRow {
  id: string;
  name?: string;
  date?: string;
  category?: string;
  amount?: number;
  currency?: string;
  vendor?: string;
  status?: string;
  notes?: string;
  [key: string]: unknown;
}

export interface FertilizationRow {
  id: string;
  date?: string;
  bed?: string;
  input?: string;
  qtyKg?: number;
  method?: string;
  worker?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface FieldsRow {
  id: string;
  code?: string;
  name?: string;
  notes?: string;
  rows?: number;
  shadehouse?: string;
  [key: string]: unknown;
}

export interface FiscalRow {
  id: string;
  name?: string;
  cai?: string;
  rtn?: string;
  rangeStart?: string;
  rangeEnd?: string;
  expiry?: string;
  total?: number;
  next?: number;
  requestDate?: string;
  active?: boolean;
  [key: string]: unknown;
}

export interface FoliarRow {
  id: string;
  sampleDate?: string;
  reportDate?: string;
  lab?: string;
  labCode?: string;
  crop?: string;
  bed?: string;
  n?: number;
  p?: number;
  k?: number;
  ca?: number;
  mg?: number;
  fe?: number;
  zn?: number;
  mn?: number;
  cu?: number;
  b?: number;
  s?: number;
  primaryName?: string;
  [key: string]: unknown;
}

export interface HarvestRow {
  id: string;
  date?: string;
  qty?: number;
  quality?: string;
  worker?: string;
  bed?: string;
  plant?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface InputComponentsRow {
  id: string;
  input?: string;
  component?: string;
  percentage?: number;
  notes?: string;
  [key: string]: unknown;
}

export interface InputsRow {
  id: string;
  name?: string;
  category?: string;
  method?: string;
  safety?: number;
  brand?: string;
  composition?: string;
  [key: string]: unknown;
}

export interface InvoicesRow {
  id: string;
  number?: string;
  customer?: string;
  date?: string;
  dueDate?: string;
  week?: number;
  subtotal?: number;
  isv?: number;
  total?: number;
  balance?: number;
  status?: string;
  [key: string]: unknown;
}

export interface IrrigationRow {
  id: string;
  date?: string;
  liters?: number;
  method?: string;
  bed?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface MaterialsRow {
  id: string;
  code?: string;
  name?: string;
  category?: string;
  unit?: string;
  partNumber?: string;
  reorderLevel?: number;
  lastUnitCost?: number;
  active?: boolean;
  notes?: string;
  supplier?: string;
  [key: string]: unknown;
}

export interface OrdersRow {
  id: string;
  number?: string;
  customer?: string;
  date?: string;
  delivery?: string;
  status?: string;
  total?: number;
  [key: string]: unknown;
}

export interface PackingRow {
  id: string;
  code?: string;
  boxNumber?: number;
  barcode?: string;
  quantity?: number;
  size?: string;
  grossWeight?: number;
  netWeight?: number;
  unitPrice?: number;
  lineTotal?: number;
  packedBy?: string;
  workerId?: string;
  packingType?: string;
  bundleSize?: number;
  productType?: string;
  cuttingType?: string;
  totalWeight?: number;
  packingDate?: string;
  completed?: boolean;
  plant?: string;
  bed?: string;
  shipment?: string;
  order?: string;
  invoice?: string;
  [key: string]: unknown;
}

export interface PaymentsRow {
  id: string;
  code?: string;
  type?: string;
  date?: string;
  counterparty?: string;
  amount?: number;
  currency?: string;
  reference?: string;
  method?: string;
  status?: string;
  notes?: string;
  bankAccount?: string;
  invoice?: string;
  [key: string]: unknown;
}

export interface PlantingsRow {
  id: string;
  date?: string;
  qty?: number;
  plant?: string;
  bed?: string;
  season?: string;
  position?: string;
  purpose?: string;
  current?: boolean;
  primaryName?: string;
  [key: string]: unknown;
}

export interface PlantsRow {
  id: string;
  code?: string;
  name?: string;
  latin?: string;
  variety?: string;
  patent?: boolean;
  patentNum?: string;
  patentHolder?: string;
  patentExpiry?: string;
  plantsPerBed?: number;
  plantsPerBasketRow?: number;
  grownIn?: string;
  shadeNeeded?: string;
  growthWeeksMinMarAug?: number;
  growthWeeksMaxMarAug?: number;
  harvestWeeksMarAug?: number;
  pruningWeeksMarAug?: number;
  growthWeeksMinSepFeb?: number;
  growthWeeksMaxSepFeb?: number;
  harvestWeeksSepFeb?: number;
  pruningWeeksSepFeb?: number;
  active?: boolean;
  [key: string]: unknown;
}

export interface PlantSizesRow {
  id: string;
  code?: string;
  plant?: string;
  size?: string;
  cuttingsPerBox?: number;
  bundleSize?: number;
  productType?: string;
  cuttingType?: string;
  active?: boolean;
  notes?: string;
  [key: string]: unknown;
}

export interface PricesRow {
  id: string;
  plant?: string;
  season?: string;
  customer?: string;
  priceExt?: number;
  priceInt?: number;
  from?: string;
  to?: string;
  active?: boolean;
  primaryName?: string;
  [key: string]: unknown;
}

export interface ProjectionsRow {
  id: string;
  plant?: string;
  season?: string;
  week?: number;
  size?: string;
  projectedQty?: number;
  orderedQty?: number;
  confirmedQty?: number;
  surplus?: number;
  shortfall?: number;
  status?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface PruningRow {
  id: string;
  date?: string;
  bed?: string;
  plant?: string;
  week?: number;
  bedsPruned?: number;
  cuttingsEstimated?: number;
  worker?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface PurchaseOrdersRow {
  id: string;
  number?: string;
  supplier?: string;
  date?: string;
  delivery?: string;
  description?: string;
  amount?: number;
  currency?: string;
  status?: string;
  notes?: string;
  [key: string]: unknown;
}

export interface SeasonsRow {
  id: string;
  name?: string;
  start?: string;
  end?: string;
  description?: string;
  active?: boolean;
  [key: string]: unknown;
}

export interface ShadehousesRow {
  id: string;
  name?: string;
  code?: string;
  location?: string;
  coordinates?: string;
  length?: number;
  width?: number;
  capacity?: number;
  fieldCapacity?: number;
  active?: boolean;
  [key: string]: unknown;
}

export interface ShipmentsRow {
  id: string;
  code?: string;
  date?: string;
  carrier?: string;
  awb?: string;
  status?: string;
  etd?: string;
  eta?: string;
  notes?: string;
  customer?: string;
  order?: string;
  invoice?: string;
  [key: string]: unknown;
}

export interface SoilRow {
  id: string;
  sampleDate?: string;
  reportDate?: string;
  lab?: string;
  labCode?: string;
  reportNumber?: string;
  crop?: string;
  bed?: string;
  texture?: string;
  sand?: number;
  silt?: number;
  clay?: number;
  ph?: number;
  organicCarbon?: number;
  organicMatter?: number;
  nTotal?: number;
  al?: number;
  alSaturation?: number;
  ce?: number;
  cl?: number;
  cic?: number;
  ca?: number;
  mg?: number;
  k?: number;
  na?: number;
  cice?: number;
  caSat?: number;
  mgSat?: number;
  kSat?: number;
  caMg?: number;
  mgK?: number;
  caK?: number;
  caMgK?: number;
  cu?: number;
  fe?: number;
  mn?: number;
  zn?: number;
  b?: number;
  s?: number;
  p?: number;
  primaryName?: string;
  [key: string]: unknown;
}

export interface SolarRadiationRow {
  id: string;
  code?: string;
  date?: string;
  megajoules?: number;
  source?: string;
  notes?: string;
  [key: string]: unknown;
}

export interface StatementsRow {
  id: string;
  code?: string;
  date?: string;
  description?: string;
  amount?: number;
  balance?: number;
  reconciled?: boolean;
  notes?: string;
  bankAccount?: string;
  matchedTo?: string;
  [key: string]: unknown;
}

export interface StockMovementsRow {
  id: string;
  code?: string;
  date?: string;
  type?: string;
  quantity?: number;
  unitCost?: number;
  issuedTo?: string;
  notes?: string;
  material?: string;
  input?: string;
  purchaseOrder?: string;
  bed?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface SubstrateMaterialsRow {
  id: string;
  name?: string;
  category?: string;
  waterRetention?: string;
  active?: boolean;
  notes?: string;
  [key: string]: unknown;
}

export interface SuppliersRow {
  id: string;
  name?: string;
  code?: string;
  category?: string;
  contact?: string;
  phone?: string;
  email?: string;
  taxId?: string;
  terms?: string;
  active?: boolean;
  notes?: string;
  [key: string]: unknown;
}

export interface TasksRow {
  id: string;
  title?: string;
  type?: string;
  due?: string;
  assigned?: string;
  priority?: string;
  status?: string;
  notes?: string;
  [key: string]: unknown;
}

export interface TimesheetsRow {
  id: string;
  date?: string;
  activity?: string;
  hours?: number;
  pieces?: number;
  boxes?: number;
  cost?: number;
  notes?: string;
  worker?: string;
  bed?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface TreatmentsRow {
  id: string;
  date?: string;
  type?: string;
  worker?: string;
  temp?: number;
  humidity?: number;
  ph?: number;
  bed?: string;
  input?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface WeightRow {
  id: string;
  date?: string;
  packingBox?: string;
  awb?: string;
  avgLeafWeight?: number;
  netWeight?: number;
  grossWeight?: number;
  dryMatterPct?: number;
  notes?: string;
  primaryName?: string;
  [key: string]: unknown;
}

export interface WorkersRow {
  id: string;
  name?: string;
  code?: string;
  role?: string;
  phone?: string;
  identity?: string;
  hireDate?: string;
  hourlyRate?: number;
  pieceRate?: number;
  active?: boolean;
  notes?: string;
  [key: string]: unknown;
}
