/**
 * generate-docs.mjs — write dataverse/DATA_MODEL.md from the schema JSON.
 *
 * The schema file is the single source of truth. Documenting the model by hand
 * guarantees drift, so this regenerates the whole document instead. Run it
 * after ANY schema change:
 *
 *   npm run dataverse:docs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const SCHEMA = join(REPO_ROOT, 'dataverse', 'farmtrack.dataverse.schema.json')
const OUT = join(REPO_ROOT, 'dataverse', 'DATA_MODEL.md')

const schema = JSON.parse(readFileSync(SCHEMA, 'utf8'))
const byName = new Map(schema.tables.map((t) => [t.schemaName, t]))

/** Anchor link for a table heading. */
const anchor = (t) => `#${t.displayName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|')

/** Which tables point AT this one, so each section shows both directions. */
function incoming(target) {
  const out = []
  for (const t of schema.tables) {
    for (const c of t.columns) {
      if (c.type === 'lookup' && c.relatedTable === target.schemaName) {
        out.push({ from: t, via: c })
      }
    }
  }
  return out
}

function typeLabel(c) {
  switch (c.type) {
    case 'string': return `Text(${c.maxLength ?? 100})`
    case 'memo': return `Text area(${c.maxLength ?? 2000})`
    case 'decimal': return `Decimal(${c.precision ?? 2})`
    case 'currency': return `Currency(${c.precision ?? 2})`
    case 'autonumber': return `Autonumber`
    case 'lookup': return `Lookup`
    case 'choice': return `Choice`
    case 'date': return `Date only`
    case 'datetime': return `Date and time`
    case 'integer': return `Whole number`
    case 'boolean': return `Yes/No`
    default: return c.type
  }
}

const lines = []
const totalColumns = schema.tables.reduce((n, t) => n + t.columns.length, 0)
const totalLookups = schema.tables.reduce(
  (n, t) => n + t.columns.filter((c) => c.type === 'lookup').length, 0
)

lines.push(`# Broton Verde Nursery — Data Model`)
lines.push('')
lines.push('> Generated from `dataverse/farmtrack.dataverse.schema.json` by')
lines.push('> `npm run dataverse:docs`. **Do not edit by hand** — change the schema and')
lines.push('> regenerate, otherwise this document and the database will disagree.')
lines.push('')
lines.push('| | |')
lines.push('|---|---|')
lines.push(`| Solution | \`${schema.solutionName}\` |`)
lines.push(`| Publisher prefix | \`${schema.publisherPrefix}_\` |`)
lines.push(`| Version | ${schema.version} |`)
lines.push(`| Tables | ${schema.tables.length} |`)
lines.push(`| Columns | ${totalColumns} |`)
lines.push(`| Relationships | ${totalLookups} |`)
lines.push('')

lines.push('## Conventions')
lines.push('')
lines.push('- **Every table\'s primary column is a Dataverse autonumber** — `SH-0001`,')
lines.push('  `PLT-0001`, and so on. These are generated by the platform and are not')
lines.push('  editable in the app.')
lines.push('- **Dates** use `Date only` behaviour where no time is meaningful. Storing a')
lines.push('  date-only value as `UserLocal` shifts it a day for downstream readers.')
lines.push('- **Deletes are referential, never parental.** A required lookup restricts the')
lines.push('  delete; an optional one clears the link. Cascade would make the relationship')
lines.push('  parental, and a child may have only one parent.')
lines.push('- **Composition is a relationship, not columns.** An input\'s guaranteed')
lines.push('  analysis lives in `Input Component` lines, so a product may declare any')
lines.push('  number of nutrients or active ingredients.')
lines.push('')

lines.push('## Tables')
lines.push('')
lines.push('| Table | Logical name | ID format | Columns | Purpose |')
lines.push('|---|---|---|---|---|')
for (const t of schema.tables) {
  const primary = t.columns.find((c) => c.isPrimaryName)
  const fmt = primary?.autoNumberFormat?.replace('{SEQNUM:4}', '0001') ?? '—'
  lines.push(
    `| [${t.displayName}](${anchor(t)}) | \`${t.schemaName.toLowerCase()}\` | \`${fmt}\` | ${t.columns.length} | ${esc(t.description ?? '')} |`
  )
}
lines.push('')

lines.push('## Relationships')
lines.push('')
lines.push('| Child | Lookup column | Parent | On delete |')
lines.push('|---|---|---|---|')
for (const t of schema.tables) {
  for (const c of t.columns.filter((x) => x.type === 'lookup')) {
    const parent = byName.get(c.relatedTable)
    lines.push(
      `| ${t.displayName} | \`${c.schemaName.toLowerCase()}\` | ${parent?.displayName ?? c.relatedTable} | ${c.required ? 'Restrict' : 'Remove link'} |`
    )
  }
}
lines.push('')

lines.push('---')
lines.push('')
for (const t of schema.tables) {
  const primary = t.columns.find((c) => c.isPrimaryName)
  lines.push(`## ${t.displayName}`)
  lines.push('')
  lines.push(`\`${t.schemaName.toLowerCase()}\` · ${t.ownershipType === 'OrganizationOwned' ? 'Organization-owned' : 'User-owned'}`)
  lines.push('')
  if (t.description) { lines.push(t.description); lines.push('') }
  if (primary?.autoNumberFormat) {
    lines.push(`**Record ID:** \`${primary.schemaName.toLowerCase()}\` — format \`${primary.autoNumberFormat}\`, e.g. \`${primary.autoNumberFormat.replace('{SEQNUM:4}', '0001')}\`.`)
    lines.push('')
  }

  lines.push('| Column | Display name | Type | Req. | Description |')
  lines.push('|---|---|---|:--:|---|')
  for (const c of t.columns) {
    let type = typeLabel(c)
    if (c.type === 'lookup') {
      const parent = byName.get(c.relatedTable)
      type = `Lookup → [${parent?.displayName ?? c.relatedTable}](${parent ? anchor(parent) : '#'})`
    }
    const flag = c.isPrimaryName ? ' 🔑' : ''
    lines.push(
      `| \`${c.schemaName.toLowerCase()}\`${flag} | ${esc(c.displayName)} | ${type} | ${c.required ? '✓' : ''} | ${esc(c.description)} |`
    )
  }
  lines.push('')

  const choices = t.columns.filter((c) => c.type === 'choice')
  if (choices.length) {
    lines.push('<details><summary>Choice values</summary>')
    lines.push('')
    for (const c of choices) {
      lines.push(`**${c.displayName}** (\`${c.schemaName.toLowerCase()}\`)`)
      lines.push('')
      lines.push('| Value | Label |')
      lines.push('|---|---|')
      for (const o of c.options) lines.push(`| ${o.value} | ${esc(o.label)} |`)
      lines.push('')
    }
    lines.push('</details>')
    lines.push('')
  }

  const refs = incoming(t)
  if (refs.length) {
    lines.push(`**Referenced by:** ${refs.map((r) => `${r.from.displayName} (\`${r.via.schemaName.toLowerCase()}\`)`).join(', ')}`)
    lines.push('')
  }
}

writeFileSync(OUT, lines.join('\n'), 'utf8')
console.log(`Wrote ${OUT}`)
console.log(`  ${schema.tables.length} tables · ${totalColumns} columns · ${totalLookups} relationships`)
