/**
 * The same country list the app carries, for the import scripts.
 *
 * Generated by scripts/dataverse/generate-countries.mjs — do not edit by hand.
 */
export const COUNTRIES = [
  {
    "code": "AF",
    "code3": "AFG",
    "numeric": 4,
    "name": "Afghanistan",
    "aliases": [
      "Afghanistan"
    ],
    "currency": "AFN"
  },
  {
    "code": "AX",
    "code3": "ALA",
    "numeric": 248,
    "name": "Åland Islands",
    "aliases": [
      "Åland Islands"
    ],
    "currency": "EUR"
  },
  {
    "code": "AL",
    "code3": "ALB",
    "numeric": 8,
    "name": "Albania",
    "aliases": [
      "Albania"
    ],
    "currency": "ALL"
  },
  {
    "code": "DZ",
    "code3": "DZA",
    "numeric": 12,
    "name": "Algeria",
    "aliases": [
      "Algeria"
    ],
    "currency": "DZD"
  },
  {
    "code": "AS",
    "code3": "ASM",
    "numeric": 16,
    "name": "American Samoa",
    "aliases": [
      "American Samoa"
    ],
    "currency": "USD"
  },
  {
    "code": "AD",
    "code3": "AND",
    "numeric": 20,
    "name": "Andorra",
    "aliases": [
      "Andorra"
    ],
    "currency": "EUR"
  },
  {
    "code": "AO",
    "code3": "AGO",
    "numeric": 24,
    "name": "Angola",
    "aliases": [
      "Angola"
    ],
    "currency": "AOA"
  },
  {
    "code": "AI",
    "code3": "AIA",
    "numeric": 660,
    "name": "Anguilla",
    "aliases": [
      "Anguilla"
    ],
    "currency": "XCD"
  },
  {
    "code": "AQ",
    "code3": "ATA",
    "numeric": 10,
    "name": "Antarctica",
    "aliases": [
      "Antarctica"
    ],
    "currency": ""
  },
  {
    "code": "AG",
    "code3": "ATG",
    "numeric": 28,
    "name": "Antigua & Barbuda",
    "aliases": [
      "Antigua & Barbuda",
      "Antigua and Barbuda"
    ],
    "currency": "XCD"
  },
  {
    "code": "AR",
    "code3": "ARG",
    "numeric": 32,
    "name": "Argentina",
    "aliases": [
      "Argentina"
    ],
    "currency": "ARS"
  },
  {
    "code": "AM",
    "code3": "ARM",
    "numeric": 51,
    "name": "Armenia",
    "aliases": [
      "Armenia"
    ],
    "currency": "AMD"
  },
  {
    "code": "AW",
    "code3": "ABW",
    "numeric": 533,
    "name": "Aruba",
    "aliases": [
      "Aruba"
    ],
    "currency": "AWG"
  },
  {
    "code": "AU",
    "code3": "AUS",
    "numeric": 36,
    "name": "Australia",
    "aliases": [
      "Australia"
    ],
    "currency": "AUD"
  },
  {
    "code": "AT",
    "code3": "AUT",
    "numeric": 40,
    "name": "Austria",
    "aliases": [
      "Austria"
    ],
    "currency": "EUR"
  },
  {
    "code": "AZ",
    "code3": "AZE",
    "numeric": 31,
    "name": "Azerbaijan",
    "aliases": [
      "Azerbaijan"
    ],
    "currency": "AZN"
  },
  {
    "code": "BS",
    "code3": "BHS",
    "numeric": 44,
    "name": "Bahamas",
    "aliases": [
      "Bahamas",
      "Bahamas (the)"
    ],
    "currency": "BSD"
  },
  {
    "code": "BH",
    "code3": "BHR",
    "numeric": 48,
    "name": "Bahrain",
    "aliases": [
      "Bahrain"
    ],
    "currency": "BHD"
  },
  {
    "code": "BD",
    "code3": "BGD",
    "numeric": 50,
    "name": "Bangladesh",
    "aliases": [
      "Bangladesh"
    ],
    "currency": "BDT"
  },
  {
    "code": "BB",
    "code3": "BRB",
    "numeric": 52,
    "name": "Barbados",
    "aliases": [
      "Barbados"
    ],
    "currency": "BBD"
  },
  {
    "code": "BY",
    "code3": "BLR",
    "numeric": 112,
    "name": "Belarus",
    "aliases": [
      "Belarus"
    ],
    "currency": "BYN"
  },
  {
    "code": "BE",
    "code3": "BEL",
    "numeric": 56,
    "name": "Belgium",
    "aliases": [
      "Belgium"
    ],
    "currency": "EUR"
  },
  {
    "code": "BZ",
    "code3": "BLZ",
    "numeric": 84,
    "name": "Belize",
    "aliases": [
      "Belize"
    ],
    "currency": "BZD"
  },
  {
    "code": "BJ",
    "code3": "BEN",
    "numeric": 204,
    "name": "Benin",
    "aliases": [
      "Benin"
    ],
    "currency": "XOF"
  },
  {
    "code": "BM",
    "code3": "BMU",
    "numeric": 60,
    "name": "Bermuda",
    "aliases": [
      "Bermuda"
    ],
    "currency": "BMD"
  },
  {
    "code": "BT",
    "code3": "BTN",
    "numeric": 64,
    "name": "Bhutan",
    "aliases": [
      "Bhutan"
    ],
    "currency": "INR"
  },
  {
    "code": "BO",
    "code3": "BOL",
    "numeric": 68,
    "name": "Bolivia",
    "aliases": [
      "Bolivia",
      "Bolivia (Plurinational State of)"
    ],
    "currency": "BOB"
  },
  {
    "code": "BA",
    "code3": "BIH",
    "numeric": 70,
    "name": "Bosnia",
    "aliases": [
      "Bosnia",
      "Bosnia and Herzegovina"
    ],
    "currency": "BAM"
  },
  {
    "code": "BW",
    "code3": "BWA",
    "numeric": 72,
    "name": "Botswana",
    "aliases": [
      "Botswana"
    ],
    "currency": "BWP"
  },
  {
    "code": "BV",
    "code3": "BVT",
    "numeric": 74,
    "name": "Bouvet Island",
    "aliases": [
      "Bouvet Island"
    ],
    "currency": "NOK"
  },
  {
    "code": "BR",
    "code3": "BRA",
    "numeric": 76,
    "name": "Brazil",
    "aliases": [
      "Brazil"
    ],
    "currency": "BRL"
  },
  {
    "code": "IO",
    "code3": "IOT",
    "numeric": 86,
    "name": "British Indian Ocean Territory",
    "aliases": [
      "British Indian Ocean Territory"
    ],
    "currency": "USD"
  },
  {
    "code": "VG",
    "code3": "VGB",
    "numeric": 92,
    "name": "British Virgin Islands",
    "aliases": [
      "British Virgin Islands"
    ],
    "currency": "USD"
  },
  {
    "code": "BN",
    "code3": "BRN",
    "numeric": 96,
    "name": "Brunei",
    "aliases": [
      "Brunei",
      "Brunei Darussalam"
    ],
    "currency": "BND"
  },
  {
    "code": "BG",
    "code3": "BGR",
    "numeric": 100,
    "name": "Bulgaria",
    "aliases": [
      "Bulgaria"
    ],
    "currency": "EUR"
  },
  {
    "code": "BF",
    "code3": "BFA",
    "numeric": 854,
    "name": "Burkina Faso",
    "aliases": [
      "Burkina Faso"
    ],
    "currency": "XOF"
  },
  {
    "code": "BI",
    "code3": "BDI",
    "numeric": 108,
    "name": "Burundi",
    "aliases": [
      "Burundi"
    ],
    "currency": "BIF"
  },
  {
    "code": "KH",
    "code3": "KHM",
    "numeric": 116,
    "name": "Cambodia",
    "aliases": [
      "Cambodia"
    ],
    "currency": "KHR"
  },
  {
    "code": "CM",
    "code3": "CMR",
    "numeric": 120,
    "name": "Cameroon",
    "aliases": [
      "Cameroon"
    ],
    "currency": "XAF"
  },
  {
    "code": "CA",
    "code3": "CAN",
    "numeric": 124,
    "name": "Canada",
    "aliases": [
      "Canada"
    ],
    "currency": "CAD"
  },
  {
    "code": "CV",
    "code3": "CPV",
    "numeric": 132,
    "name": "Cape Verde",
    "aliases": [
      "Cape Verde",
      "Cabo Verde"
    ],
    "currency": "CVE"
  },
  {
    "code": "BQ",
    "code3": "BES",
    "numeric": 535,
    "name": "Caribbean Netherlands",
    "aliases": [
      "Caribbean Netherlands",
      "Bonaire, Sint Eustatius and Saba"
    ],
    "currency": "USD"
  },
  {
    "code": "KY",
    "code3": "CYM",
    "numeric": 136,
    "name": "Cayman Islands",
    "aliases": [
      "Cayman Islands"
    ],
    "currency": "KYD"
  },
  {
    "code": "CF",
    "code3": "CAF",
    "numeric": 140,
    "name": "Central African Republic",
    "aliases": [
      "Central African Republic",
      "Central African Republic (the)"
    ],
    "currency": "XAF"
  },
  {
    "code": "TD",
    "code3": "TCD",
    "numeric": 148,
    "name": "Chad",
    "aliases": [
      "Chad"
    ],
    "currency": "XAF"
  },
  {
    "code": "CL",
    "code3": "CHL",
    "numeric": 152,
    "name": "Chile",
    "aliases": [
      "Chile"
    ],
    "currency": "CLP"
  },
  {
    "code": "CN",
    "code3": "CHN",
    "numeric": 156,
    "name": "China",
    "aliases": [
      "China"
    ],
    "currency": "CNY"
  },
  {
    "code": "CX",
    "code3": "CXR",
    "numeric": 162,
    "name": "Christmas Island",
    "aliases": [
      "Christmas Island"
    ],
    "currency": "AUD"
  },
  {
    "code": "CC",
    "code3": "CCK",
    "numeric": 166,
    "name": "Cocos Islands",
    "aliases": [
      "Cocos Islands",
      "Cocos (Keeling) Islands"
    ],
    "currency": "AUD"
  },
  {
    "code": "CO",
    "code3": "COL",
    "numeric": 170,
    "name": "Colombia",
    "aliases": [
      "Colombia"
    ],
    "currency": "COP"
  },
  {
    "code": "KM",
    "code3": "COM",
    "numeric": 174,
    "name": "Comoros",
    "aliases": [
      "Comoros",
      "Comoros (the)"
    ],
    "currency": "KMF"
  },
  {
    "code": "CG",
    "code3": "COG",
    "numeric": 178,
    "name": "Congo - Brazzaville",
    "aliases": [
      "Congo - Brazzaville",
      "Congo",
      "Congo (the)"
    ],
    "currency": "XAF"
  },
  {
    "code": "CD",
    "code3": "COD",
    "numeric": 180,
    "name": "Congo - Kinshasa",
    "aliases": [
      "Congo - Kinshasa",
      "Democratic Republic of the Congo",
      "Democratic Republic of the Congo (the)"
    ],
    "currency": "CDF"
  },
  {
    "code": "CK",
    "code3": "COK",
    "numeric": 184,
    "name": "Cook Islands",
    "aliases": [
      "Cook Islands",
      "Cook Islands (the) **"
    ],
    "currency": "NZD"
  },
  {
    "code": "CR",
    "code3": "CRI",
    "numeric": 188,
    "name": "Costa Rica",
    "aliases": [
      "Costa Rica"
    ],
    "currency": "CRC"
  },
  {
    "code": "CI",
    "code3": "CIV",
    "numeric": 384,
    "name": "Côte d’Ivoire",
    "aliases": [
      "Côte d’Ivoire",
      "Ivory Coast"
    ],
    "currency": "XOF"
  },
  {
    "code": "HR",
    "code3": "HRV",
    "numeric": 191,
    "name": "Croatia",
    "aliases": [
      "Croatia"
    ],
    "currency": "EUR"
  },
  {
    "code": "CU",
    "code3": "CUB",
    "numeric": 192,
    "name": "Cuba",
    "aliases": [
      "Cuba"
    ],
    "currency": "CUP"
  },
  {
    "code": "CW",
    "code3": "CUW",
    "numeric": 531,
    "name": "Curaçao",
    "aliases": [
      "Curaçao"
    ],
    "currency": "XCG"
  },
  {
    "code": "CY",
    "code3": "CYP",
    "numeric": 196,
    "name": "Cyprus",
    "aliases": [
      "Cyprus"
    ],
    "currency": "EUR"
  },
  {
    "code": "CZ",
    "code3": "CZE",
    "numeric": 203,
    "name": "Czechia",
    "aliases": [
      "Czechia"
    ],
    "currency": "CZK"
  },
  {
    "code": "DK",
    "code3": "DNK",
    "numeric": 208,
    "name": "Denmark",
    "aliases": [
      "Denmark"
    ],
    "currency": "DKK"
  },
  {
    "code": "DJ",
    "code3": "DJI",
    "numeric": 262,
    "name": "Djibouti",
    "aliases": [
      "Djibouti"
    ],
    "currency": "DJF"
  },
  {
    "code": "DM",
    "code3": "DMA",
    "numeric": 212,
    "name": "Dominica",
    "aliases": [
      "Dominica"
    ],
    "currency": "XCD"
  },
  {
    "code": "DO",
    "code3": "DOM",
    "numeric": 214,
    "name": "Dominican Republic",
    "aliases": [
      "Dominican Republic",
      "Dominican Republic (the)"
    ],
    "currency": "DOP"
  },
  {
    "code": "EC",
    "code3": "ECU",
    "numeric": 218,
    "name": "Ecuador",
    "aliases": [
      "Ecuador"
    ],
    "currency": "USD"
  },
  {
    "code": "EG",
    "code3": "EGY",
    "numeric": 818,
    "name": "Egypt",
    "aliases": [
      "Egypt"
    ],
    "currency": "EGP"
  },
  {
    "code": "SV",
    "code3": "SLV",
    "numeric": 222,
    "name": "El Salvador",
    "aliases": [
      "El Salvador"
    ],
    "currency": "SVC"
  },
  {
    "code": "GQ",
    "code3": "GNQ",
    "numeric": 226,
    "name": "Equatorial Guinea",
    "aliases": [
      "Equatorial Guinea"
    ],
    "currency": "XAF"
  },
  {
    "code": "ER",
    "code3": "ERI",
    "numeric": 232,
    "name": "Eritrea",
    "aliases": [
      "Eritrea"
    ],
    "currency": "ERN"
  },
  {
    "code": "EE",
    "code3": "EST",
    "numeric": 233,
    "name": "Estonia",
    "aliases": [
      "Estonia"
    ],
    "currency": "EUR"
  },
  {
    "code": "SZ",
    "code3": "SWZ",
    "numeric": 748,
    "name": "Eswatini",
    "aliases": [
      "Eswatini"
    ],
    "currency": "SZL"
  },
  {
    "code": "ET",
    "code3": "ETH",
    "numeric": 231,
    "name": "Ethiopia",
    "aliases": [
      "Ethiopia"
    ],
    "currency": "ETB"
  },
  {
    "code": "FK",
    "code3": "FLK",
    "numeric": 238,
    "name": "Falkland Islands",
    "aliases": [
      "Falkland Islands"
    ],
    "currency": "FKP"
  },
  {
    "code": "FO",
    "code3": "FRO",
    "numeric": 234,
    "name": "Faroe Islands",
    "aliases": [
      "Faroe Islands"
    ],
    "currency": "DKK"
  },
  {
    "code": "FJ",
    "code3": "FJI",
    "numeric": 242,
    "name": "Fiji",
    "aliases": [
      "Fiji"
    ],
    "currency": "FJD"
  },
  {
    "code": "FI",
    "code3": "FIN",
    "numeric": 246,
    "name": "Finland",
    "aliases": [
      "Finland"
    ],
    "currency": "EUR"
  },
  {
    "code": "FR",
    "code3": "FRA",
    "numeric": 250,
    "name": "France",
    "aliases": [
      "France"
    ],
    "currency": "EUR"
  },
  {
    "code": "GF",
    "code3": "GUF",
    "numeric": 254,
    "name": "French Guiana",
    "aliases": [
      "French Guiana"
    ],
    "currency": "EUR"
  },
  {
    "code": "PF",
    "code3": "PYF",
    "numeric": 258,
    "name": "French Polynesia",
    "aliases": [
      "French Polynesia"
    ],
    "currency": "XPF"
  },
  {
    "code": "TF",
    "code3": "ATF",
    "numeric": 260,
    "name": "French Southern Territories",
    "aliases": [
      "French Southern Territories"
    ],
    "currency": "EUR"
  },
  {
    "code": "GA",
    "code3": "GAB",
    "numeric": 266,
    "name": "Gabon",
    "aliases": [
      "Gabon"
    ],
    "currency": "XAF"
  },
  {
    "code": "GM",
    "code3": "GMB",
    "numeric": 270,
    "name": "Gambia",
    "aliases": [
      "Gambia",
      "Gambia (the)"
    ],
    "currency": "GMD"
  },
  {
    "code": "GE",
    "code3": "GEO",
    "numeric": 268,
    "name": "Georgia",
    "aliases": [
      "Georgia"
    ],
    "currency": "GEL"
  },
  {
    "code": "DE",
    "code3": "DEU",
    "numeric": 276,
    "name": "Germany",
    "aliases": [
      "Germany"
    ],
    "currency": "EUR"
  },
  {
    "code": "GH",
    "code3": "GHA",
    "numeric": 288,
    "name": "Ghana",
    "aliases": [
      "Ghana"
    ],
    "currency": "GHS"
  },
  {
    "code": "GI",
    "code3": "GIB",
    "numeric": 292,
    "name": "Gibraltar",
    "aliases": [
      "Gibraltar"
    ],
    "currency": "GIP"
  },
  {
    "code": "GR",
    "code3": "GRC",
    "numeric": 300,
    "name": "Greece",
    "aliases": [
      "Greece"
    ],
    "currency": "EUR"
  },
  {
    "code": "GL",
    "code3": "GRL",
    "numeric": 304,
    "name": "Greenland",
    "aliases": [
      "Greenland"
    ],
    "currency": "DKK"
  },
  {
    "code": "GD",
    "code3": "GRD",
    "numeric": 308,
    "name": "Grenada",
    "aliases": [
      "Grenada"
    ],
    "currency": "XCD"
  },
  {
    "code": "GP",
    "code3": "GLP",
    "numeric": 312,
    "name": "Guadeloupe",
    "aliases": [
      "Guadeloupe"
    ],
    "currency": "EUR"
  },
  {
    "code": "GU",
    "code3": "GUM",
    "numeric": 316,
    "name": "Guam",
    "aliases": [
      "Guam"
    ],
    "currency": "USD"
  },
  {
    "code": "GT",
    "code3": "GTM",
    "numeric": 320,
    "name": "Guatemala",
    "aliases": [
      "Guatemala"
    ],
    "currency": "GTQ"
  },
  {
    "code": "GG",
    "code3": "GGY",
    "numeric": 831,
    "name": "Guernsey",
    "aliases": [
      "Guernsey"
    ],
    "currency": "GBP"
  },
  {
    "code": "GN",
    "code3": "GIN",
    "numeric": 324,
    "name": "Guinea",
    "aliases": [
      "Guinea"
    ],
    "currency": "GNF"
  },
  {
    "code": "GW",
    "code3": "GNB",
    "numeric": 624,
    "name": "Guinea-Bissau",
    "aliases": [
      "Guinea-Bissau"
    ],
    "currency": "XOF"
  },
  {
    "code": "GY",
    "code3": "GUY",
    "numeric": 328,
    "name": "Guyana",
    "aliases": [
      "Guyana"
    ],
    "currency": "GYD"
  },
  {
    "code": "HT",
    "code3": "HTI",
    "numeric": 332,
    "name": "Haiti",
    "aliases": [
      "Haiti"
    ],
    "currency": "HTG"
  },
  {
    "code": "HM",
    "code3": "HMD",
    "numeric": 334,
    "name": "Heard & McDonald Islands",
    "aliases": [
      "Heard & McDonald Islands",
      "Heard Island and McDonald Islands"
    ],
    "currency": "AUD"
  },
  {
    "code": "HN",
    "code3": "HND",
    "numeric": 340,
    "name": "Honduras",
    "aliases": [
      "Honduras"
    ],
    "currency": "HNL"
  },
  {
    "code": "HK",
    "code3": "HKG",
    "numeric": 344,
    "name": "Hong Kong",
    "aliases": [
      "Hong Kong",
      "China, Hong Kong Special Administrative Region"
    ],
    "currency": "HKD"
  },
  {
    "code": "HU",
    "code3": "HUN",
    "numeric": 348,
    "name": "Hungary",
    "aliases": [
      "Hungary"
    ],
    "currency": "HUF"
  },
  {
    "code": "IS",
    "code3": "ISL",
    "numeric": 352,
    "name": "Iceland",
    "aliases": [
      "Iceland"
    ],
    "currency": "ISK"
  },
  {
    "code": "IN",
    "code3": "IND",
    "numeric": 356,
    "name": "India",
    "aliases": [
      "India"
    ],
    "currency": "INR"
  },
  {
    "code": "ID",
    "code3": "IDN",
    "numeric": 360,
    "name": "Indonesia",
    "aliases": [
      "Indonesia"
    ],
    "currency": "IDR"
  },
  {
    "code": "IR",
    "code3": "IRN",
    "numeric": 364,
    "name": "Iran",
    "aliases": [
      "Iran",
      "Iran (Islamic Republic of)"
    ],
    "currency": "IRR"
  },
  {
    "code": "IQ",
    "code3": "IRQ",
    "numeric": 368,
    "name": "Iraq",
    "aliases": [
      "Iraq"
    ],
    "currency": "IQD"
  },
  {
    "code": "IE",
    "code3": "IRL",
    "numeric": 372,
    "name": "Ireland",
    "aliases": [
      "Ireland"
    ],
    "currency": "EUR"
  },
  {
    "code": "IM",
    "code3": "IMN",
    "numeric": 833,
    "name": "Isle of Man",
    "aliases": [
      "Isle of Man"
    ],
    "currency": "GBP"
  },
  {
    "code": "IL",
    "code3": "ISR",
    "numeric": 376,
    "name": "Israel",
    "aliases": [
      "Israel"
    ],
    "currency": "ILS"
  },
  {
    "code": "IT",
    "code3": "ITA",
    "numeric": 380,
    "name": "Italy",
    "aliases": [
      "Italy"
    ],
    "currency": "EUR"
  },
  {
    "code": "JM",
    "code3": "JAM",
    "numeric": 388,
    "name": "Jamaica",
    "aliases": [
      "Jamaica"
    ],
    "currency": "JMD"
  },
  {
    "code": "JP",
    "code3": "JPN",
    "numeric": 392,
    "name": "Japan",
    "aliases": [
      "Japan"
    ],
    "currency": "JPY"
  },
  {
    "code": "JE",
    "code3": "JEY",
    "numeric": 832,
    "name": "Jersey",
    "aliases": [
      "Jersey"
    ],
    "currency": "GBP"
  },
  {
    "code": "JO",
    "code3": "JOR",
    "numeric": 400,
    "name": "Jordan",
    "aliases": [
      "Jordan"
    ],
    "currency": "JOD"
  },
  {
    "code": "KZ",
    "code3": "KAZ",
    "numeric": 398,
    "name": "Kazakhstan",
    "aliases": [
      "Kazakhstan"
    ],
    "currency": "KZT"
  },
  {
    "code": "KE",
    "code3": "KEN",
    "numeric": 404,
    "name": "Kenya",
    "aliases": [
      "Kenya"
    ],
    "currency": "KES"
  },
  {
    "code": "KI",
    "code3": "KIR",
    "numeric": 296,
    "name": "Kiribati",
    "aliases": [
      "Kiribati"
    ],
    "currency": "AUD"
  },
  {
    "code": "KW",
    "code3": "KWT",
    "numeric": 414,
    "name": "Kuwait",
    "aliases": [
      "Kuwait"
    ],
    "currency": "KWD"
  },
  {
    "code": "KG",
    "code3": "KGZ",
    "numeric": 417,
    "name": "Kyrgyzstan",
    "aliases": [
      "Kyrgyzstan"
    ],
    "currency": "KGS"
  },
  {
    "code": "LA",
    "code3": "LAO",
    "numeric": 418,
    "name": "Laos",
    "aliases": [
      "Laos",
      "Lao People's Democratic Republic",
      "Lao People's Democratic Republic (the)"
    ],
    "currency": "LAK"
  },
  {
    "code": "LV",
    "code3": "LVA",
    "numeric": 428,
    "name": "Latvia",
    "aliases": [
      "Latvia"
    ],
    "currency": "EUR"
  },
  {
    "code": "LB",
    "code3": "LBN",
    "numeric": 422,
    "name": "Lebanon",
    "aliases": [
      "Lebanon"
    ],
    "currency": "LBP"
  },
  {
    "code": "LS",
    "code3": "LSO",
    "numeric": 426,
    "name": "Lesotho",
    "aliases": [
      "Lesotho"
    ],
    "currency": "LSL"
  },
  {
    "code": "LR",
    "code3": "LBR",
    "numeric": 430,
    "name": "Liberia",
    "aliases": [
      "Liberia"
    ],
    "currency": "LRD"
  },
  {
    "code": "LY",
    "code3": "LBY",
    "numeric": 434,
    "name": "Libya",
    "aliases": [
      "Libya"
    ],
    "currency": "LYD"
  },
  {
    "code": "LI",
    "code3": "LIE",
    "numeric": 438,
    "name": "Liechtenstein",
    "aliases": [
      "Liechtenstein"
    ],
    "currency": "CHF"
  },
  {
    "code": "LT",
    "code3": "LTU",
    "numeric": 440,
    "name": "Lithuania",
    "aliases": [
      "Lithuania"
    ],
    "currency": "EUR"
  },
  {
    "code": "LU",
    "code3": "LUX",
    "numeric": 442,
    "name": "Luxembourg",
    "aliases": [
      "Luxembourg"
    ],
    "currency": "EUR"
  },
  {
    "code": "MO",
    "code3": "MAC",
    "numeric": 446,
    "name": "Macao",
    "aliases": [
      "Macao",
      "China, Macao Special Administrative Region"
    ],
    "currency": "MOP"
  },
  {
    "code": "MG",
    "code3": "MDG",
    "numeric": 450,
    "name": "Madagascar",
    "aliases": [
      "Madagascar"
    ],
    "currency": "MGA"
  },
  {
    "code": "MW",
    "code3": "MWI",
    "numeric": 454,
    "name": "Malawi",
    "aliases": [
      "Malawi"
    ],
    "currency": "MWK"
  },
  {
    "code": "MY",
    "code3": "MYS",
    "numeric": 458,
    "name": "Malaysia",
    "aliases": [
      "Malaysia"
    ],
    "currency": "MYR"
  },
  {
    "code": "MV",
    "code3": "MDV",
    "numeric": 462,
    "name": "Maldives",
    "aliases": [
      "Maldives"
    ],
    "currency": "MVR"
  },
  {
    "code": "ML",
    "code3": "MLI",
    "numeric": 466,
    "name": "Mali",
    "aliases": [
      "Mali"
    ],
    "currency": "XOF"
  },
  {
    "code": "MT",
    "code3": "MLT",
    "numeric": 470,
    "name": "Malta",
    "aliases": [
      "Malta"
    ],
    "currency": "EUR"
  },
  {
    "code": "MH",
    "code3": "MHL",
    "numeric": 584,
    "name": "Marshall Islands",
    "aliases": [
      "Marshall Islands",
      "Marshall Islands (the)"
    ],
    "currency": "USD"
  },
  {
    "code": "MQ",
    "code3": "MTQ",
    "numeric": 474,
    "name": "Martinique",
    "aliases": [
      "Martinique"
    ],
    "currency": "EUR"
  },
  {
    "code": "MR",
    "code3": "MRT",
    "numeric": 478,
    "name": "Mauritania",
    "aliases": [
      "Mauritania"
    ],
    "currency": "MRU"
  },
  {
    "code": "MU",
    "code3": "MUS",
    "numeric": 480,
    "name": "Mauritius",
    "aliases": [
      "Mauritius"
    ],
    "currency": "MUR"
  },
  {
    "code": "YT",
    "code3": "MYT",
    "numeric": 175,
    "name": "Mayotte",
    "aliases": [
      "Mayotte"
    ],
    "currency": "EUR"
  },
  {
    "code": "MX",
    "code3": "MEX",
    "numeric": 484,
    "name": "Mexico",
    "aliases": [
      "Mexico"
    ],
    "currency": "MXN"
  },
  {
    "code": "FM",
    "code3": "FSM",
    "numeric": 583,
    "name": "Micronesia",
    "aliases": [
      "Micronesia",
      "Micronesia (Federated States of)"
    ],
    "currency": "USD"
  },
  {
    "code": "MD",
    "code3": "MDA",
    "numeric": 498,
    "name": "Moldova",
    "aliases": [
      "Moldova",
      "Republic of Moldova",
      "Republic of Moldova (the)"
    ],
    "currency": "MDL"
  },
  {
    "code": "MC",
    "code3": "MCO",
    "numeric": 492,
    "name": "Monaco",
    "aliases": [
      "Monaco"
    ],
    "currency": "EUR"
  },
  {
    "code": "MN",
    "code3": "MNG",
    "numeric": 496,
    "name": "Mongolia",
    "aliases": [
      "Mongolia"
    ],
    "currency": "MNT"
  },
  {
    "code": "ME",
    "code3": "MNE",
    "numeric": 499,
    "name": "Montenegro",
    "aliases": [
      "Montenegro"
    ],
    "currency": "EUR"
  },
  {
    "code": "MS",
    "code3": "MSR",
    "numeric": 500,
    "name": "Montserrat",
    "aliases": [
      "Montserrat"
    ],
    "currency": "XCD"
  },
  {
    "code": "MA",
    "code3": "MAR",
    "numeric": 504,
    "name": "Morocco",
    "aliases": [
      "Morocco"
    ],
    "currency": "MAD"
  },
  {
    "code": "MZ",
    "code3": "MOZ",
    "numeric": 508,
    "name": "Mozambique",
    "aliases": [
      "Mozambique"
    ],
    "currency": "MZN"
  },
  {
    "code": "MM",
    "code3": "MMR",
    "numeric": 104,
    "name": "Myanmar",
    "aliases": [
      "Myanmar"
    ],
    "currency": "MMK"
  },
  {
    "code": "NA",
    "code3": "NAM",
    "numeric": 516,
    "name": "Namibia",
    "aliases": [
      "Namibia"
    ],
    "currency": "NAD"
  },
  {
    "code": "NR",
    "code3": "NRU",
    "numeric": 520,
    "name": "Nauru",
    "aliases": [
      "Nauru"
    ],
    "currency": "AUD"
  },
  {
    "code": "NP",
    "code3": "NPL",
    "numeric": 524,
    "name": "Nepal",
    "aliases": [
      "Nepal"
    ],
    "currency": "NPR"
  },
  {
    "code": "NL",
    "code3": "NLD",
    "numeric": 528,
    "name": "Netherlands",
    "aliases": [
      "Netherlands",
      "Netherlands (the)"
    ],
    "currency": "EUR"
  },
  {
    "code": "NC",
    "code3": "NCL",
    "numeric": 540,
    "name": "New Caledonia",
    "aliases": [
      "New Caledonia"
    ],
    "currency": "XPF"
  },
  {
    "code": "NZ",
    "code3": "NZL",
    "numeric": 554,
    "name": "New Zealand",
    "aliases": [
      "New Zealand"
    ],
    "currency": "NZD"
  },
  {
    "code": "NI",
    "code3": "NIC",
    "numeric": 558,
    "name": "Nicaragua",
    "aliases": [
      "Nicaragua"
    ],
    "currency": "NIO"
  },
  {
    "code": "NE",
    "code3": "NER",
    "numeric": 562,
    "name": "Niger",
    "aliases": [
      "Niger",
      "Niger (the)"
    ],
    "currency": "XOF"
  },
  {
    "code": "NG",
    "code3": "NGA",
    "numeric": 566,
    "name": "Nigeria",
    "aliases": [
      "Nigeria"
    ],
    "currency": "NGN"
  },
  {
    "code": "NU",
    "code3": "NIU",
    "numeric": 570,
    "name": "Niue",
    "aliases": [
      "Niue",
      "Niue **"
    ],
    "currency": "NZD"
  },
  {
    "code": "NF",
    "code3": "NFK",
    "numeric": 574,
    "name": "Norfolk Island",
    "aliases": [
      "Norfolk Island"
    ],
    "currency": "AUD"
  },
  {
    "code": "KP",
    "code3": "PRK",
    "numeric": 408,
    "name": "North Korea",
    "aliases": [
      "North Korea",
      "Democratic People's Republic of Korea",
      "Democratic People's Republic of Korea (the)"
    ],
    "currency": "KPW"
  },
  {
    "code": "MK",
    "code3": "MKD",
    "numeric": 807,
    "name": "North Macedonia",
    "aliases": [
      "North Macedonia"
    ],
    "currency": "MKD"
  },
  {
    "code": "MP",
    "code3": "MNP",
    "numeric": 580,
    "name": "Northern Mariana Islands",
    "aliases": [
      "Northern Mariana Islands"
    ],
    "currency": "USD"
  },
  {
    "code": "NO",
    "code3": "NOR",
    "numeric": 578,
    "name": "Norway",
    "aliases": [
      "Norway"
    ],
    "currency": "NOK"
  },
  {
    "code": "OM",
    "code3": "OMN",
    "numeric": 512,
    "name": "Oman",
    "aliases": [
      "Oman"
    ],
    "currency": "OMR"
  },
  {
    "code": "PK",
    "code3": "PAK",
    "numeric": 586,
    "name": "Pakistan",
    "aliases": [
      "Pakistan"
    ],
    "currency": "PKR"
  },
  {
    "code": "PW",
    "code3": "PLW",
    "numeric": 585,
    "name": "Palau",
    "aliases": [
      "Palau"
    ],
    "currency": "USD"
  },
  {
    "code": "PS",
    "code3": "PSE",
    "numeric": 275,
    "name": "Palestine",
    "aliases": [
      "Palestine",
      "State of Palestine",
      "State of Palestine (the) *"
    ],
    "currency": ""
  },
  {
    "code": "PA",
    "code3": "PAN",
    "numeric": 591,
    "name": "Panama",
    "aliases": [
      "Panama"
    ],
    "currency": "PAB"
  },
  {
    "code": "PG",
    "code3": "PNG",
    "numeric": 598,
    "name": "Papua New Guinea",
    "aliases": [
      "Papua New Guinea"
    ],
    "currency": "PGK"
  },
  {
    "code": "PY",
    "code3": "PRY",
    "numeric": 600,
    "name": "Paraguay",
    "aliases": [
      "Paraguay"
    ],
    "currency": "PYG"
  },
  {
    "code": "PE",
    "code3": "PER",
    "numeric": 604,
    "name": "Peru",
    "aliases": [
      "Peru"
    ],
    "currency": "PEN"
  },
  {
    "code": "PH",
    "code3": "PHL",
    "numeric": 608,
    "name": "Philippines",
    "aliases": [
      "Philippines",
      "Philippines (the)"
    ],
    "currency": "PHP"
  },
  {
    "code": "PN",
    "code3": "PCN",
    "numeric": 612,
    "name": "Pitcairn",
    "aliases": [
      "Pitcairn"
    ],
    "currency": "NZD"
  },
  {
    "code": "PL",
    "code3": "POL",
    "numeric": 616,
    "name": "Poland",
    "aliases": [
      "Poland"
    ],
    "currency": "PLN"
  },
  {
    "code": "PT",
    "code3": "PRT",
    "numeric": 620,
    "name": "Portugal",
    "aliases": [
      "Portugal"
    ],
    "currency": "EUR"
  },
  {
    "code": "PR",
    "code3": "PRI",
    "numeric": 630,
    "name": "Puerto Rico",
    "aliases": [
      "Puerto Rico"
    ],
    "currency": "USD"
  },
  {
    "code": "QA",
    "code3": "QAT",
    "numeric": 634,
    "name": "Qatar",
    "aliases": [
      "Qatar"
    ],
    "currency": "QAR"
  },
  {
    "code": "RE",
    "code3": "REU",
    "numeric": 638,
    "name": "Réunion",
    "aliases": [
      "Réunion"
    ],
    "currency": "EUR"
  },
  {
    "code": "RO",
    "code3": "ROU",
    "numeric": 642,
    "name": "Romania",
    "aliases": [
      "Romania"
    ],
    "currency": "RON"
  },
  {
    "code": "RU",
    "code3": "RUS",
    "numeric": 643,
    "name": "Russia",
    "aliases": [
      "Russia",
      "Russian Federation",
      "Russian Federation (the)"
    ],
    "currency": "RUB"
  },
  {
    "code": "RW",
    "code3": "RWA",
    "numeric": 646,
    "name": "Rwanda",
    "aliases": [
      "Rwanda"
    ],
    "currency": "RWF"
  },
  {
    "code": "WS",
    "code3": "WSM",
    "numeric": 882,
    "name": "Samoa",
    "aliases": [
      "Samoa"
    ],
    "currency": "WST"
  },
  {
    "code": "SM",
    "code3": "SMR",
    "numeric": 674,
    "name": "San Marino",
    "aliases": [
      "San Marino"
    ],
    "currency": "EUR"
  },
  {
    "code": "ST",
    "code3": "STP",
    "numeric": 678,
    "name": "São Tomé & Príncipe",
    "aliases": [
      "São Tomé & Príncipe",
      "Sao Tome and Principe"
    ],
    "currency": "STN"
  },
  {
    "code": "SA",
    "code3": "SAU",
    "numeric": 682,
    "name": "Saudi Arabia",
    "aliases": [
      "Saudi Arabia"
    ],
    "currency": "SAR"
  },
  {
    "code": "SN",
    "code3": "SEN",
    "numeric": 686,
    "name": "Senegal",
    "aliases": [
      "Senegal"
    ],
    "currency": "XOF"
  },
  {
    "code": "RS",
    "code3": "SRB",
    "numeric": 688,
    "name": "Serbia",
    "aliases": [
      "Serbia"
    ],
    "currency": "RSD"
  },
  {
    "code": "SC",
    "code3": "SYC",
    "numeric": 690,
    "name": "Seychelles",
    "aliases": [
      "Seychelles"
    ],
    "currency": "SCR"
  },
  {
    "code": "SL",
    "code3": "SLE",
    "numeric": 694,
    "name": "Sierra Leone",
    "aliases": [
      "Sierra Leone"
    ],
    "currency": "SLE"
  },
  {
    "code": "SG",
    "code3": "SGP",
    "numeric": 702,
    "name": "Singapore",
    "aliases": [
      "Singapore"
    ],
    "currency": "SGD"
  },
  {
    "code": "SX",
    "code3": "SXM",
    "numeric": 534,
    "name": "Sint Maarten",
    "aliases": [
      "Sint Maarten",
      "Sint Maarten (Dutch part)"
    ],
    "currency": "XCG"
  },
  {
    "code": "SK",
    "code3": "SVK",
    "numeric": 703,
    "name": "Slovakia",
    "aliases": [
      "Slovakia"
    ],
    "currency": "EUR"
  },
  {
    "code": "SI",
    "code3": "SVN",
    "numeric": 705,
    "name": "Slovenia",
    "aliases": [
      "Slovenia"
    ],
    "currency": "EUR"
  },
  {
    "code": "SB",
    "code3": "SLB",
    "numeric": 90,
    "name": "Solomon Islands",
    "aliases": [
      "Solomon Islands"
    ],
    "currency": "SBD"
  },
  {
    "code": "SO",
    "code3": "SOM",
    "numeric": 706,
    "name": "Somalia",
    "aliases": [
      "Somalia"
    ],
    "currency": "SOS"
  },
  {
    "code": "ZA",
    "code3": "ZAF",
    "numeric": 710,
    "name": "South Africa",
    "aliases": [
      "South Africa"
    ],
    "currency": "ZAR"
  },
  {
    "code": "GS",
    "code3": "SGS",
    "numeric": 239,
    "name": "South Georgia & South Sandwich Islands",
    "aliases": [
      "South Georgia & South Sandwich Islands",
      "South Georgia and the South Sandwich Islands"
    ],
    "currency": ""
  },
  {
    "code": "KR",
    "code3": "KOR",
    "numeric": 410,
    "name": "South Korea",
    "aliases": [
      "South Korea",
      "Republic of Korea",
      "Republic of Korea (the)"
    ],
    "currency": "KRW"
  },
  {
    "code": "SS",
    "code3": "SSD",
    "numeric": 728,
    "name": "South Sudan",
    "aliases": [
      "South Sudan"
    ],
    "currency": "SSP"
  },
  {
    "code": "ES",
    "code3": "ESP",
    "numeric": 724,
    "name": "Spain",
    "aliases": [
      "Spain"
    ],
    "currency": "EUR"
  },
  {
    "code": "LK",
    "code3": "LKA",
    "numeric": 144,
    "name": "Sri Lanka",
    "aliases": [
      "Sri Lanka"
    ],
    "currency": "LKR"
  },
  {
    "code": "BL",
    "code3": "BLM",
    "numeric": 652,
    "name": "St. Barthélemy",
    "aliases": [
      "St. Barthélemy",
      "Saint Barthélemy"
    ],
    "currency": "EUR"
  },
  {
    "code": "SH",
    "code3": "SHN",
    "numeric": 654,
    "name": "St. Helena",
    "aliases": [
      "St. Helena",
      "Saint Helena"
    ],
    "currency": "SHP"
  },
  {
    "code": "KN",
    "code3": "KNA",
    "numeric": 659,
    "name": "St. Kitts & Nevis",
    "aliases": [
      "St. Kitts & Nevis",
      "Saint Kitts and Nevis"
    ],
    "currency": "XCD"
  },
  {
    "code": "LC",
    "code3": "LCA",
    "numeric": 662,
    "name": "St. Lucia",
    "aliases": [
      "St. Lucia",
      "Saint Lucia"
    ],
    "currency": "XCD"
  },
  {
    "code": "MF",
    "code3": "MAF",
    "numeric": 663,
    "name": "St. Martin",
    "aliases": [
      "St. Martin",
      "Saint Martin (French Part)"
    ],
    "currency": "EUR"
  },
  {
    "code": "PM",
    "code3": "SPM",
    "numeric": 666,
    "name": "St. Pierre & Miquelon",
    "aliases": [
      "St. Pierre & Miquelon",
      "Saint Pierre and Miquelon"
    ],
    "currency": "EUR"
  },
  {
    "code": "VC",
    "code3": "VCT",
    "numeric": 670,
    "name": "St. Vincent & Grenadines",
    "aliases": [
      "St. Vincent & Grenadines",
      "Saint Vincent and the Grenadines"
    ],
    "currency": "XCD"
  },
  {
    "code": "SD",
    "code3": "SDN",
    "numeric": 729,
    "name": "Sudan",
    "aliases": [
      "Sudan",
      "Sudan (the)"
    ],
    "currency": "SDG"
  },
  {
    "code": "SR",
    "code3": "SUR",
    "numeric": 740,
    "name": "Suriname",
    "aliases": [
      "Suriname"
    ],
    "currency": "SRD"
  },
  {
    "code": "SJ",
    "code3": "SJM",
    "numeric": 744,
    "name": "Svalbard & Jan Mayen",
    "aliases": [
      "Svalbard & Jan Mayen",
      "Svalbard and Jan Mayen Islands"
    ],
    "currency": "NOK"
  },
  {
    "code": "SE",
    "code3": "SWE",
    "numeric": 752,
    "name": "Sweden",
    "aliases": [
      "Sweden"
    ],
    "currency": "SEK"
  },
  {
    "code": "CH",
    "code3": "CHE",
    "numeric": 756,
    "name": "Switzerland",
    "aliases": [
      "Switzerland"
    ],
    "currency": "CHF"
  },
  {
    "code": "SY",
    "code3": "SYR",
    "numeric": 760,
    "name": "Syria",
    "aliases": [
      "Syria",
      "Syrian Arab Republic",
      "Syrian Arab Republic (the)"
    ],
    "currency": "SYP"
  },
  {
    "code": "TW",
    "code3": "TWN",
    "numeric": 158,
    "name": "Taiwan",
    "aliases": [
      "Taiwan"
    ],
    "currency": "TWD"
  },
  {
    "code": "TJ",
    "code3": "TJK",
    "numeric": 762,
    "name": "Tajikistan",
    "aliases": [
      "Tajikistan"
    ],
    "currency": "TJS"
  },
  {
    "code": "TZ",
    "code3": "TZA",
    "numeric": 834,
    "name": "Tanzania",
    "aliases": [
      "Tanzania",
      "United Republic of Tanzania",
      "United Republic of Tanzania (the)"
    ],
    "currency": "TZS"
  },
  {
    "code": "TH",
    "code3": "THA",
    "numeric": 764,
    "name": "Thailand",
    "aliases": [
      "Thailand"
    ],
    "currency": "THB"
  },
  {
    "code": "TL",
    "code3": "TLS",
    "numeric": 626,
    "name": "Timor-Leste",
    "aliases": [
      "Timor-Leste"
    ],
    "currency": "USD"
  },
  {
    "code": "TG",
    "code3": "TGO",
    "numeric": 768,
    "name": "Togo",
    "aliases": [
      "Togo"
    ],
    "currency": "XOF"
  },
  {
    "code": "TK",
    "code3": "TKL",
    "numeric": 772,
    "name": "Tokelau",
    "aliases": [
      "Tokelau"
    ],
    "currency": "NZD"
  },
  {
    "code": "TO",
    "code3": "TON",
    "numeric": 776,
    "name": "Tonga",
    "aliases": [
      "Tonga"
    ],
    "currency": "TOP"
  },
  {
    "code": "TT",
    "code3": "TTO",
    "numeric": 780,
    "name": "Trinidad & Tobago",
    "aliases": [
      "Trinidad & Tobago",
      "Trinidad and Tobago"
    ],
    "currency": "TTD"
  },
  {
    "code": "TN",
    "code3": "TUN",
    "numeric": 788,
    "name": "Tunisia",
    "aliases": [
      "Tunisia"
    ],
    "currency": "TND"
  },
  {
    "code": "TR",
    "code3": "TUR",
    "numeric": 792,
    "name": "Türkiye",
    "aliases": [
      "Türkiye"
    ],
    "currency": ""
  },
  {
    "code": "TM",
    "code3": "TKM",
    "numeric": 795,
    "name": "Turkmenistan",
    "aliases": [
      "Turkmenistan"
    ],
    "currency": "TMT"
  },
  {
    "code": "TC",
    "code3": "TCA",
    "numeric": 796,
    "name": "Turks & Caicos Islands",
    "aliases": [
      "Turks & Caicos Islands",
      "Turks and Caicos Islands"
    ],
    "currency": "USD"
  },
  {
    "code": "TV",
    "code3": "TUV",
    "numeric": 798,
    "name": "Tuvalu",
    "aliases": [
      "Tuvalu"
    ],
    "currency": "AUD"
  },
  {
    "code": "UM",
    "code3": "UMI",
    "numeric": 581,
    "name": "U.S. Outlying Islands",
    "aliases": [
      "U.S. Outlying Islands",
      "United States Minor Outlying Islands"
    ],
    "currency": "USD"
  },
  {
    "code": "VI",
    "code3": "VIR",
    "numeric": 850,
    "name": "U.S. Virgin Islands",
    "aliases": [
      "U.S. Virgin Islands",
      "United States Virgin Islands"
    ],
    "currency": "USD"
  },
  {
    "code": "UG",
    "code3": "UGA",
    "numeric": 800,
    "name": "Uganda",
    "aliases": [
      "Uganda"
    ],
    "currency": "UGX"
  },
  {
    "code": "UA",
    "code3": "UKR",
    "numeric": 804,
    "name": "Ukraine",
    "aliases": [
      "Ukraine"
    ],
    "currency": "UAH"
  },
  {
    "code": "AE",
    "code3": "ARE",
    "numeric": 784,
    "name": "United Arab Emirates",
    "aliases": [
      "United Arab Emirates",
      "United Arab Emirates (the)"
    ],
    "currency": "AED"
  },
  {
    "code": "GB",
    "code3": "GBR",
    "numeric": 826,
    "name": "United Kingdom of Great Britain and Northern Ireland",
    "aliases": [
      "UK",
      "United Kingdom of Great Britain and Northern Ireland",
      "United Kingdom of Great Britain and Northern Ireland (the)"
    ],
    "currency": "GBP"
  },
  {
    "code": "US",
    "code3": "USA",
    "numeric": 840,
    "name": "United States of America",
    "aliases": [
      "US",
      "United States of America",
      "United States",
      "United States of America (the)"
    ],
    "currency": "USD"
  },
  {
    "code": "UY",
    "code3": "URY",
    "numeric": 858,
    "name": "Uruguay",
    "aliases": [
      "Uruguay"
    ],
    "currency": "UYU"
  },
  {
    "code": "UZ",
    "code3": "UZB",
    "numeric": 860,
    "name": "Uzbekistan",
    "aliases": [
      "Uzbekistan"
    ],
    "currency": "UZS"
  },
  {
    "code": "VU",
    "code3": "VUT",
    "numeric": 548,
    "name": "Vanuatu",
    "aliases": [
      "Vanuatu"
    ],
    "currency": "VUV"
  },
  {
    "code": "VA",
    "code3": "VAT",
    "numeric": 336,
    "name": "Vatican City",
    "aliases": [
      "Vatican City",
      "Holy See",
      "Holy See (the) *"
    ],
    "currency": "EUR"
  },
  {
    "code": "VE",
    "code3": "VEN",
    "numeric": 862,
    "name": "Venezuela",
    "aliases": [
      "Venezuela",
      "Venezuela (Bolivarian Republic of)"
    ],
    "currency": "VES"
  },
  {
    "code": "VN",
    "code3": "VNM",
    "numeric": 704,
    "name": "Vietnam",
    "aliases": [
      "Vietnam",
      "Viet Nam"
    ],
    "currency": "VND"
  },
  {
    "code": "WF",
    "code3": "WLF",
    "numeric": 876,
    "name": "Wallis & Futuna",
    "aliases": [
      "Wallis & Futuna",
      "Wallis and Futuna Islands"
    ],
    "currency": "XPF"
  },
  {
    "code": "EH",
    "code3": "ESH",
    "numeric": 732,
    "name": "Western Sahara",
    "aliases": [
      "Western Sahara"
    ],
    "currency": "MAD"
  },
  {
    "code": "YE",
    "code3": "YEM",
    "numeric": 887,
    "name": "Yemen",
    "aliases": [
      "Yemen"
    ],
    "currency": "YER"
  },
  {
    "code": "ZM",
    "code3": "ZMB",
    "numeric": 894,
    "name": "Zambia",
    "aliases": [
      "Zambia"
    ],
    "currency": "ZMW"
  },
  {
    "code": "ZW",
    "code3": "ZWE",
    "numeric": 716,
    "name": "Zimbabwe",
    "aliases": [
      "Zimbabwe"
    ],
    "currency": "ZWG"
  }
];
