"""
The land around the nursery, from public elevation tiles.

The survey stops at the shadehouse block: 104 m by 174 m of ground measured to
the centimetre, and then nothing. In the 3D view that block floats on an
infinite flat plane, which is not what El Olvido looks like — it sits in a
valley with the ground rising to the east.

This fills in the surroundings from the AWS terrain tiles (Mapzen's terrarium
encoding of, among others, the Copernicus and SRTM DEMs; public, no key). At
zoom 13 a pixel is about 19 m here, which is far too coarse for the block
itself — the survey is two orders of magnitude better and keeps that job. It is
plenty for the hillside a kilometre out.

  height = (red * 256 + green + blue / 256) - 32768   metres

Run: python3 scripts/survey/extract_surround.py
"""
import io
import math
import urllib.request
from pathlib import Path

import numpy as np
from PIL import Image

# The nursery, from services/site.ts.
SITE_LAT, SITE_LON = 14.9786, -87.9531
ZOOM = 13
#: How far out to model, each way. Beyond this the ground is off camera anyway.
HALF_SPAN_M = 1200.0
#: Samples across the surround grid. 41 gives a 60 m step — coarser than the
#: tiles, deliberately: this is context, not terrain anyone measures against.
SAMPLES = 41

OUT = Path("src/services/terrainSurround.generated.ts")
TILES = "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png"


def tile_of(lat, lon, z):
    """Slippy-map tile containing a coordinate, with the fraction inside it."""
    n = 2.0 ** z
    x = (lon + 180.0) / 360.0 * n
    rad = math.radians(lat)
    y = (1.0 - math.asinh(math.tan(rad)) / math.pi) / 2.0 * n
    return x, y


def fetch(z, x, y):
    url = TILES.format(z=z, x=int(x), y=int(y))
    with urllib.request.urlopen(url, timeout=60) as res:
        return Image.open(io.BytesIO(res.read())).convert("RGB")


def height_field():
    """A grid of metres above sea level, centred on the nursery."""
    fx, fy = tile_of(SITE_LAT, SITE_LON, ZOOM)
    # Three tiles each way covers ±1.2 km at this latitude with room to spare.
    tiles = {}
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            tiles[(int(fx) + dx, int(fy) + dy)] = np.asarray(
                fetch(ZOOM, int(fx) + dx, int(fy) + dy), dtype=np.float64
            )

    # Metres per degree here, so the span can be walked in lat/lon.
    m_per_deg_lat = 110574.0
    m_per_deg_lon = 111320.0 * math.cos(math.radians(SITE_LAT))

    grid = np.zeros((SAMPLES, SAMPLES))
    for i in range(SAMPLES):
        # Row 0 is the north edge, matching the scene's -Z.
        north = HALF_SPAN_M - 2 * HALF_SPAN_M * i / (SAMPLES - 1)
        for j in range(SAMPLES):
            east = -HALF_SPAN_M + 2 * HALF_SPAN_M * j / (SAMPLES - 1)
            lat = SITE_LAT + north / m_per_deg_lat
            lon = SITE_LON + east / m_per_deg_lon
            tx, ty = tile_of(lat, lon, ZOOM)
            tile = tiles[(int(tx), int(ty))]
            px = min(int((tx - int(tx)) * tile.shape[1]), tile.shape[1] - 1)
            py = min(int((ty - int(ty)) * tile.shape[0]), tile.shape[0] - 1)
            r, g, b = tile[py, px]
            grid[i, j] = (r * 256.0 + g + b / 256.0) - 32768.0
    return grid


def main():
    grid = height_field()
    rows = ",\n  ".join(
        "[" + ", ".join(f"{v:.1f}" for v in row) + "]" for row in grid
    )
    OUT.write_text(f'''/**
 * GENERATED by scripts/survey/extract_surround.py — do not edit.
 *
 * The land around the nursery: {SAMPLES} by {SAMPLES} samples over
 * {int(2 * HALF_SPAN_M)} m each way, metres above sea level, read from the AWS
 * terrain tiles (terrarium encoding, zoom {ZOOM}, about 19 m a pixel here).
 *
 * Coarse on purpose. Inside the shadehouse block the survey is two orders of
 * magnitude better and keeps that job; this is the valley the block sits in,
 * so the 3D view stops standing it on an infinite flat plane.
 *
 * Regenerate with: python3 scripts/survey/extract_surround.py
 */

/** Samples each way. Row 0 is the north edge. */
export const SURROUND_SAMPLES = {SAMPLES};
/** Half the modelled extent, in metres from the nursery. */
export const SURROUND_HALF_SPAN_M = {HALF_SPAN_M};

/** Metres above sea level, row-major: [north-to-south][west-to-east]. */
export const SURROUND_M: number[][] = [
  {rows},
];

export const SURROUND_LOW_M = {grid.min():.1f};
export const SURROUND_HIGH_M = {grid.max():.1f};
''')
    print(f"  {SAMPLES}x{SAMPLES} samples, {grid.min():.0f}–{grid.max():.0f} m")


if __name__ == "__main__":
    main()
